### ISSUE TITLE
Slice() function question

### ISSUE THREAD

**Issue by yrsunn** [fitushar/3D-Medical-Imaging-Preprocessing-All-you-need#1]
Hi,

when I run the resize or crop function in your code, I got the error here:

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

It happens at the slicer object.

Do you know why this happened? Thank you so much!

**Comment by MiriamBalzer** [comment]
I have the same issue. Did you find a solution for yourself?

**Comment by MiriamBalzer** [comment]
In case somebody else is having this issue: the solution should be to change the return line of this function to 
return np.pad(image[tuple(slicer)], to_padding, **kwargs)
